#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1

PROG=/usr/bin/clash
DIR=/srv/clash/

start_service() {
    procd_open_instance clash
    procd_set_param command /usr/bin/bypass-proxy $PROG -d $DIR
    procd_set_param user root
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

reload_service() {
    stop clash
    start clash
}